version: '2'
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
services:
  api:
    networks:
      mynet:
        ipv4_address: 172.16.238.101
    container_name: api
    build:
      context: .
    ports:
      - "8080:8080"
    command: ./main
    links:
      - db
    depends_on:
      - db

  db:
    container_name: db
    networks:
      mynet:
        ipv4_address: 172.16.238.201
    build:
      context: ./sql
    ports:
      - "3306:3306"
