swagger: "2.0"
info:
  description: "This is an API that communicates with the Widgets Single Page App Demo"
  version: "1.0.0"
  title: "Widgets API"
  contact:
    email: "chr.saiki@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
schemes:
- "http"
paths:
  /users:
    get:
      tags:
      - "users"
      summary: "Get all the users"
      description: ""
      operationId: "getUsers"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
        405:
          description: "Invalid input"
      security:
      - basic_auth: []

  /users/{userId}:
    get:
      tags:
      - "users"
      summary: "Get a single user by Id"
      description: "Returns a single user"
      operationId: "getUserById"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "ID of user to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "User not found"
      security:
      - basic_auth: []

  /widgets:
    get:
      tags:
      - "widgets"
      summary: "Get all the widgets"
      operationId: "getWidgets"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: "#/definitions/Widget"
      security:
      - basic_auth: []
    post:
      tags:
      - "widgets"
      summary: "Add new widgets"
      description: ""
      operationId: "addWidgets"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Widgets array that will be added"
        required: true
        schema:
          type: array
          items:
            $ref: "#/definitions/Widget"
      responses:
        200:
          description: "successful operation"
        405:
          description: "Invalid input"

  /widgets/{widgetId}:
    get:
      tags:
      - "widgets"
      summary: "Get a single widget by Id"
      operationId: "getWidgetById"
      produces:
      - "application/json"
      parameters:
      - name: "widgetId"
        in: "path"
        description: "ID of widget to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Widget"
        400:
          description: "Invalid Widget"
    put:
      tags:
      - "widgets"
      summary: "Updates a widget based on its Id"
      description: ""
      operationId: "updateWidget"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "widgetId"
        in: "path"
        description: "ID of the widget that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Widgets object that will be updated"
        required: true
        schema:
          $ref: "#/definitions/Widget"

      responses:
        200:
          description: "successful operation"
        405:
          description: "Invalid input"
      security:
      - basic_auth: []

securityDefinitions:
  basic_auth:
    type: "basic"

definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      gravatar:
        type: "string"
  Widget:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      color:
        type: "string"
      price:
        type: "string"
      inventory:
        type: "string"
      melts:
        type: "boolean"

  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
